### ISSUE TITLE
Attestation fails because --pgp-key-fingerprint is not a valid argument

### ISSUE THREAD

**Issue by otherguy** [CircleCI-Public/gcp-binary-authorization-orb#13]
The `--pgp-key-fingerprint` argument is no longer used by the GCP CLI, making builds fail:

https://github.com/CircleCI-Public/gcp-binary-authorization-orb/blob/d6e3ff50ad1a4bf1706f0f869c80074cc33b74a1/src/commands/create-attestation.yml#L257
```
ERROR: (gcloud.beta.container.binauthz.attestations.create) unrecognized arguments: --pgp-key-fingerprint=4E25EF3C8EA9CB5732ECFBB54643C84258CE89DC 

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by Jaryt** [comment]
Merged in #16

**Comment by otherguy** [comment]
@Jaryt awesome, thank you!

Could you please create a new release of this orb so we don't have to point to the dev version?

**Comment by otherguy** [comment]
@Jaryt I guess this can be closed then! Attestation works just fine :)
